library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
NEI_Total <- NEI %>% group_by(year) %>% summarize(Emissions = sum(Emissions))
years <- as.vector(NEI_Total$year)
title <- paste("Total PM2.5 Emissions (",as.character(years[1])," - ",as.character(years[length(years)]),")",sep="")
plot(NEI_Total,type="l",ylab="Emissions (in tons)",main=title)
dev.copy(png,file="plot1.png",width=480,height=480)
dev.off()